repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        language_version: python3.11
        types: [python]
        args:
          - --init-hook="import sys; sys.path.append('/Users/liborhavranek/Documents/PycharmProjects/SwapIt/venv/lib/python3.11/site-packages')"
#          - --reports=y
          - --score=y
          - --disable=C0114,C0115,C0116 # soubor trida a class musí mít svuj vlastní docstring s popisem
          - --disable=C0301 # delka radku
          - --disable=W0511 # Nebude hlásit todůčka
